In [1]:
# open npy file

import numpy as np
data = np.load(r'C:\Users\Admin\OneDrive\Desktop\Desktop\DT-Pose\data\wipose\Test_Amplitude_DWT\bend_009-frame001.npz', allow_pickle=True)

In [5]:
import mat73
data_mat = mat73.loadmat(r"C:\Users\Admin\OneDrive\Desktop\Desktop\DT-Pose\data\wipose\Test\bend_009-frame001.mat")
data_mat.keys()

dict_keys(['CSI', 'SkeletonPoints'])

In [8]:
csi = data_mat["CSI"]
ske = data_mat['SkeletonPoints']

In [ ]:
print(csi.dtype)
print(np.min(csi), np.max(csi))

float64
0.0 54.38532377656736


In [10]:
print(ske.shape)

(54,)


In [14]:
print(ske)

[1.37894043e+02 2.01325386e+02 2.02578598e+02 2.87208374e+02
 3.54465942e+02 2.00072174e+02 2.70874390e+02 3.54368103e+02
 3.51864746e+02 4.49056671e+02 5.51434631e+02 3.36840363e+02
 4.39174683e+02 5.38649231e+02 1.22940201e+02 1.18044479e+02
 1.40380630e+02 4.34683350e+02 2.80597961e+02 3.17884216e+02
 3.40368103e+02 3.27835083e+02 2.93002258e+02 2.95400330e+02
 2.62624847e+02 2.70937714e+02 3.25476166e+02 3.15474335e+02
 3.42695435e+02 3.02304626e+02 3.04943054e+02 3.30265167e+02
 2.95568909e+02 2.83047424e+02 3.32844452e+02 3.22191772e+02
 8.27377081e-01 6.61848128e-01 6.84330463e-01 8.88884127e-01
 8.27618122e-01 6.39365792e-01 2.67183959e-01 3.39344501e-01
 4.56409603e-01 6.17439151e-01 5.57545483e-01 3.19272220e-01
 5.87602317e-01 6.24153256e-01 8.73584092e-01 2.30846509e-01
 8.88585567e-01 9.17825289e-03]


In [11]:
data['CSI'].shape

(3, 90, 5)

In [12]:
data['SkeletonPoints']

array([[137.89404297, 201.32538605, 202.57859802, 287.20837402,
        354.46594238, 200.07217407, 270.87438965, 354.36810303,
        351.86474609, 449.05667114, 551.43463135, 336.84036255,
        439.17468262, 538.64923096, 122.94020081, 118.04447937,
        140.38063049, 434.68334961],
       [280.59796143, 317.88421631, 340.36810303, 327.83508301,
        293.0022583 , 295.40032959, 262.62484741, 270.93771362,
        325.47616577, 315.47433472, 342.69543457, 302.30462646,
        304.9430542 , 330.26516724, 295.56890869, 283.04742432,
        332.8444519 , 322.19177246]])

In [13]:
data['SkeletonPoints'].shape

(2, 18)

In [11]:
import yaml
with open(r"C:\Users\Admin\OneDrive\Desktop\Desktop\DT-Pose\config\wipose\pose_config.yaml", 'r') as fd:
        config = yaml.load(fd, Loader=yaml.FullLoader)

from model.hpeli.hpeli import hpelinet, hpeli_weights_init
model = hpelinet(num_keypoints=18, num_coor=2, subcarrier_num=90, num_person= 5, dataset=config['dataset_name'])

In [16]:
import yaml
with open(r"C:\Users\Admin\OneDrive\Desktop\Desktop\DT-Pose\config\wipose\pose_config.yaml", 'r') as fd:
        config = yaml.load(fd, Loader=yaml.FullLoader)

from model.hpeli.hpeli import hpelinet, hpeli_weights_init
model = hpelinet(num_keypoints=18, num_coor=2, subcarrier_num=90, num_person= 2, dataset=config['dataset_name'])

In [17]:
import torch
input_tensor = torch.randn(1, 3, 90, 5)  # Example input tensor with batch size 1
with torch.no_grad():
    output = model(input_tensor)
print(output)


(tensor([[[ 0.1430, -0.0485],
         [-0.1786, -0.0842],
         [-0.0368, -0.1456],
         [-0.0309,  0.0674],
         [-0.0487,  0.0646],
         [ 0.1332,  0.1707],
         [-0.0266, -0.0090],
         [-0.0544,  0.0148],
         [-0.0764, -0.1523],
         [-0.0694,  0.0949],
         [ 0.1254, -0.0603],
         [-0.0474, -0.0040],
         [ 0.1229,  0.0831],
         [ 0.0346,  0.0950],
         [-0.0663, -0.0568],
         [-0.0953, -0.0028],
         [-0.1764,  0.0256],
         [ 0.1634, -0.0701]]]), tensor([[0.3829, 0.4231, 0.3681, 0.3800, 0.4168, 0.4183, 0.4222, 0.3989, 0.4158,
         0.3998, 0.4038, 0.3916, 0.3715, 0.3520, 0.3898, 0.3973, 0.3718, 0.3910,
         0.4301, 0.4251, 0.3975, 0.3875, 0.3888, 0.3886, 0.4063, 0.3999, 0.4096,
         0.4161, 0.3912, 0.4037, 0.4389, 0.4369, 0.4119, 0.4054, 0.4109, 0.4299,
         0.3926, 0.4264, 0.4192, 0.4287, 0.4199, 0.4120, 0.3759, 0.4133, 0.3776,
         0.3659, 0.3956, 0.3945, 0.3615, 0.4240, 0.3958, 0.4221, 0.40

In [53]:
from model.model import *
model = MAE_ViT(image_size=(90, 5),
                        patch_size=(2,1),
                        encoder_layer=4,
                        encoder_head=4,
                        decoder_layer=2,
                        decoder_head=4,
                        emb_dim=256,
                        input_dim=3)
model = ViT_Pose_Decoder(model.encoder, keypoints=18, coor_num=2, token_num=45*5, dataset="wipose", num_person=1)

In [54]:
inp = torch.randn(1, 3, 90, 5)
with torch.no_grad():
    out = model(inp)    
    print(out)


(tensor([[[ 0.3743, -0.1117],
         [ 0.2758,  0.0624],
         [ 0.3030,  0.0434],
         [ 0.3318, -0.0961],
         [ 0.2565, -0.1185],
         [ 0.2993, -0.0053],
         [ 0.3386, -0.0615],
         [ 0.2949, -0.2213],
         [ 0.3466, -0.0104],
         [ 0.2324, -0.0734],
         [ 0.3185, -0.2200],
         [ 0.3022, -0.0048],
         [ 0.3093,  0.0195],
         [ 0.3543, -0.2373],
         [ 0.3659, -0.0682],
         [ 0.3139, -0.0666],
         [ 0.3882, -0.1378],
         [ 0.2778, -0.2232]]]), tensor([[ 0.5104,  0.1795,  0.1546,  0.0659,  0.5399, -0.1659, -0.7188,  0.4902,
          0.3245, -0.6873, -0.5966, -0.6297,  0.3480,  0.5812,  0.4775, -1.7900,
          0.4202,  0.3781,  0.1919,  0.2758, -0.8410, -0.3256,  0.0426, -0.2873,
          0.1674,  0.4991, -0.6622, -0.0350,  0.2637,  0.4684, -0.2940,  0.4113,
         -0.2910, -0.7472,  0.9100,  0.1319, -0.2783,  0.6544, -1.0215, -0.2935,
          1.0550, -0.1111,  0.5830, -0.8829, -0.3210,  0.4826, -0.235

In [3]:

from model.metafi.mynetwork import metafinet, metafi_weights_init
model = metafinet(num_keypoints=18, num_coor=2, dataset="wipose", num_person=1)

c:\Users\Admin\anaconda3\envs\dfine\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\Admin\anaconda3\envs\dfine\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet34_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet34_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [4]:
inp = torch.randn(1, 3, 90, 5)
out = model(inp)
print(out[0].shape)


torch.Size([1, 18, 2])


In [5]:
out[0]

tensor([[[-0.3539,  1.6438],
         [-1.5514,  0.8277],
         [-0.7312,  1.5237],
         [ 0.1404,  0.3777],
         [-0.4384, -1.2197],
         [-0.0387, -1.1263],
         [ 0.5702, -0.1476],
         [-0.7111, -0.5480],
         [-0.3910, -1.3520],
         [ 2.7352,  0.3801],
         [ 1.5579,  0.0488],
         [ 1.2344, -1.1225],
         [-0.1814, -1.1854],
         [-0.9136, -1.2480],
         [ 0.5247,  0.3190],
         [-0.6755,  1.2002],
         [-0.8356,  0.8232],
         [ 0.0591,  0.8054]]], grad_fn=<ViewBackward0>)

In [33]:
# calculate number of parameters
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'The model has {count_parameters(model)} trainable parameters')

The model has 5245059 trainable parameters


In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from einops import rearrange, repeat

# -------------------------
# Simple Hypergraph Convolution (HGNN) implementation (based on HGNN paper)
# H: incidence matrix (num_nodes x num_hyperedges)
# X: node features (B, num_nodes, D)
# -------------------------
class HypergraphConv(nn.Module):
    def __init__(self, in_dim, out_dim, use_bias=True):
        super().__init__()
        self.theta = nn.Linear(in_dim, out_dim, bias=use_bias)

    def forward(self, X, H):
        H = H.float()
        deg_v = torch.clamp(H.sum(1), min=1e-6)
        deg_e = torch.clamp(H.sum(0), min=1e-6)
        D_v_inv_sqrt = torch.diag(1.0 / torch.sqrt(deg_v))
        D_e_inv = torch.diag(1.0 / deg_e)
        A = D_v_inv_sqrt @ H @ D_e_inv @ H.t() @ D_v_inv_sqrt
        A = A / (A.sum(1, keepdim=True) + 1e-8)  # normalize row
        AX = torch.matmul(A, X)
        out = self.theta(AX)
        out = F.layer_norm(out, out.shape[-1:])
        return out + X if X.shape[-1] == out.shape[-1] else out

# CSI Encoder
class CSI_Encoder(nn.Module):
    def __init__(self, in_channels=3, emb_dim=256):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels, 64, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(128, emb_dim, kernel_size=3, padding=1)
        self.pool = nn.AdaptiveAvgPool2d((None, 1))  # compress frequency dimension
        self.norm = nn.LayerNorm(emb_dim)
        
    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
        x = F.relu(self.conv3(x))
        x = self.pool(x)  # B x emb_dim x H x 1
        x = x.squeeze(-1) # B x emb_dim x H
        x = rearrange(x, 'b d t -> b t d')  # B x T x D
        x = self.norm(x)
        return x  # memory


# Decoder with per-person cross-attention + HGNN refine
class MultiPersonDecoderPerPerson(nn.Module):
    def __init__(self, emb_dim=256, num_keypoints=17, num_person=2, num_layers=3, nhead=8, hgnn_hidden=256, coor_num=3):
        super().__init__()
        self.num_person = num_person
        self.num_keypoints = num_keypoints
        self.emb_dim = emb_dim

        # queries
        self.person_queries = nn.Parameter(torch.randn(num_person, emb_dim))
        self.keypoint_queries = nn.Parameter(torch.randn(num_keypoints, emb_dim))

        decoder_layer = nn.TransformerDecoderLayer(d_model=emb_dim, nhead=nhead, batch_first=True)
        self.transformer_decoder = nn.TransformerDecoder(decoder_layer, num_layers=num_layers)

        # after decoder we have embeddings per keypoint; apply HGNN (works on nodes = keypoints)
        self.hgnn1 = HypergraphConv(in_dim=emb_dim, out_dim=hgnn_hidden)
        self.hgnn2 = HypergraphConv(in_dim=hgnn_hidden, out_dim=emb_dim)

        # final head: embedding -> coord
        self.fc_out = nn.Linear(emb_dim, coor_num)

    def forward(self, memory, H):
        """
        memory: (B, T, D)
        H: incidence matrix (N=num_keypoints, E) torch tensor (shared)
        returns: coords (B, P, K, 3)
        """
        B, T, D = memory.shape
        device = memory.device

        person_q = self.person_queries.unsqueeze(0).repeat(B, 1, 1)  # B x P x D
        key_q = self.keypoint_queries.unsqueeze(0).repeat(B, 1, 1)   # B x K x D

        all_person_outputs = []
        # loop per person to get isolated cross-attention
        for p in range(self.num_person):
            # construct tgt for this person: (B, K, D)
            # broadcast person embedding and add keypoint queries (simple interaction)
            per_person_query = person_q[:, p:p+1, :]  # (B,1,D)
            tgt = per_person_query + key_q            # (B,K,D)
            # TransformerDecoder expects tgt (B, tgt_len, D) and memory (B, src_len, D)
            out_emb = self.transformer_decoder(tgt=tgt, memory=memory)  # (B, K, D)

            # Hypergraph refine: HGNN expects (B, N, D) where N = K
            out_ref1 = self.hgnn1(out_emb, H)    # (B, K, hgnn_hidden)
            out_ref2 = self.hgnn2(out_ref1, H)   # (B, K, D)

            coords = self.fc_out(out_ref2)       # (B, K, 3)
            all_person_outputs.append(coords.unsqueeze(1))  # add person dim

        # concat persons: list of (B,1,K,3) -> (B,P,K,3)
        all_person_outputs = torch.cat(all_person_outputs, dim=1)
        return all_person_outputs  # (B, P, K, 3)


class CSI_HPE_withHGNN(nn.Module):
    def __init__(self, emb_dim=128, num_keypoints=17, num_person=1, coor_num=3):
        super().__init__()
        self.encoder = CSI_Encoder(in_channels=3, emb_dim=emb_dim)
        self.decoder = MultiPersonDecoderPerPerson(emb_dim=emb_dim, num_keypoints=num_keypoints, num_person=num_person, coor_num=coor_num)

    def forward(self, x, H):
        # x: (B, C, H_time, W_freq)
        memory = self.encoder(x)  # (B, T, D)
        coords = self.decoder(memory, H)  # (B, P, K, 3)
        return coords
    
def init_csi_hpe_weights(m):
    # Conv2d
    if isinstance(m, nn.Conv2d):
        nn.init.xavier_normal_(m.weight)
        if m.bias is not None:
            nn.init.constant_(m.bias, 0)
    
    # Linear
    elif isinstance(m, nn.Linear):
        nn.init.xavier_normal_(m.weight)
        if m.bias is not None:
            nn.init.constant_(m.bias, 0)
    
    # BatchNorm / LayerNorm
    elif isinstance(m, (nn.BatchNorm1d, nn.BatchNorm2d, nn.LayerNorm)):
        nn.init.constant_(m.weight, 1)
        nn.init.constant_(m.bias, 0)
    
    # HypergraphConv (Linear theta)
    elif isinstance(m, HypergraphConv):
        nn.init.xavier_normal_(m.theta.weight)
        if m.theta.bias is not None:
            nn.init.constant_(m.theta.bias, 0)
    
    # TransformerDecoderLayer (Linear + LayerNorm)
    elif isinstance(m, nn.TransformerDecoderLayer):
        for name, param in m.named_parameters():
            if 'weight' in name:
                if param.dim() > 1:
                    nn.init.xavier_normal_(param)
                else:
                    nn.init.constant_(param, 1)
            elif 'bias' in name:
                nn.init.constant_(param, 0)

# -------------------------
# Quick test
# -------------------------
if __name__ == "__main__":
    B = 3; C = 3; T = 90; W = 5
    P = 5; K = 18; D = 256; CN = 2
    model = CSI_HPE_withHGNN(emb_dim=D, num_keypoints=K, num_person=P, coor_num=CN)
    inp = torch.randn(1,3, 90, 5)

    # example incidence H: N x E
    # simplest: per-person hyperedge connecting all K joints (E = P)
    # Here we'll create H for a single person (we can reuse same H for all persons or include person hyperedges)
    # For demonstration let's create E = K (each hyperedge = single joint) + 1 global hyperedge (all joints)
    # But standard HGNN expects meaningful H; simplest: create one hyperedge connecting all joints:
    H = torch.ones(K, 1)  # every joint belongs to the single hyperedge (all-joints)
    out = model(inp, H)
    print("out.shape", out.shape)  # (B, P, K, 3)


out.shape torch.Size([1, 5, 18, 2])


In [7]:
out

tensor([[[[-1.8023,  0.0514],
          [-1.7860,  0.2651],
          [-1.9362, -0.2768],
          [-2.0887, -0.2393],
          [-1.5071, -0.2198],
          [-1.4814,  0.0521],
          [-1.6043, -0.2418],
          [-1.8751,  0.2762],
          [-2.0711, -0.1256],
          [-2.1949, -0.2065],
          [-1.9869, -0.0716],
          [-1.7747,  0.3363],
          [-2.2216,  0.0504],
          [-1.5461, -0.3080],
          [-1.9417, -0.2109],
          [-1.5849,  0.0308],
          [-1.5969,  0.2516],
          [-1.4472, -0.3145]]]], grad_fn=<CatBackward0>)

In [59]:
x = torch.randn(2, 1, 90, 5)  # B x C x H x W

In [60]:
x = x.squeeze(1)

In [61]:
x.shape

torch.Size([2, 90, 5])

In [1]:
import torch

# Giả sử
B = 2           # batch size
K = 5           # số keypoints
emb_dim = 8     # embedding dimension
num_person = 2

# Tạo keypoint queries (B x K x emb_dim)
key_q = torch.randn(B, K, emb_dim)

# Tạo person queries (num_person x emb_dim)
person_q = torch.randn(num_person, emb_dim)

# Lặp qua từng person
for p in range(num_person):
    # Chọn person query, shape (B, 1, emb_dim)
    per_person_query = person_q[p].unsqueeze(0).unsqueeze(1).repeat(B, 1, 1)

    # Cộng với keypoint queries (broadcasting)
    tgt = per_person_query + key_q

    print(f"Person {p} query shape: {per_person_query.shape}")
    print(f"Keypoint query shape: {key_q.shape}")
    print(f"tgt shape: {tgt.shape}")
    print("-" * 40)


Person 0 query shape: torch.Size([2, 1, 8])
Keypoint query shape: torch.Size([2, 5, 8])
tgt shape: torch.Size([2, 5, 8])
----------------------------------------
Person 1 query shape: torch.Size([2, 1, 8])
Keypoint query shape: torch.Size([2, 5, 8])
tgt shape: torch.Size([2, 5, 8])
----------------------------------------


In [1]:
!pip install ninja cmake setuptools wheel
!pip install packaging

# clone mamba
!git clone https://github.com/state-spaces/mamba.git
%cd mamba

# build selective_scan
!pip install -e .

c:\Users\Admin\OneDrive\Desktop\Desktop\DT-Pose\mamba


Cloning into 'mamba'...


Obtaining file:///C:/Users/Admin/OneDrive/Desktop/Desktop/DT-Pose/mamba
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'error'


  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      C:\Users\Admin\AppData\Local\Temp\pip-build-env-4z9_l_5u\overlay\Lib\site-packages\torch\_subclasses\functional_tensor.py:279: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
        cpu = _conversion_method_template(device=torch.device("cpu"))
      
      
      torch.__version__  = 2.9.1+cpu
      
      
      <string>:118: UserWarning: mamba_ssm was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
      Traceback (most recent call last):
        File "C:\Users\Admin\anaconda3\envs\dfine\Lib\site-packages\pip\_vendor\

In [5]:
import os
import subprocess
from packaging.version import parse

def get_cuda_bare_metal_version(cuda_dir):
    nvcc_path = os.path.join(cuda_dir, "bin", "nvcc.exe")  # Windows fix

    if not os.path.exists(nvcc_path):
        raise RuntimeError(f"nvcc not found at {nvcc_path}")

    raw_output = subprocess.check_output(
        [nvcc_path, "-V"], universal_newlines=True
    )
    output = raw_output.split()
    release_idx = output.index("release") + 1
    bare_metal_ver = parse(output[release_idx].split(",")[0])

    return raw_output, bare_metal_ver

In [9]:
import torch
print(torch.version.cuda)
print(torch.cuda.is_available())


11.8
True


In [10]:
import os
print("CUDA_HOME:", os.environ.get("CUDA_HOME"))
print("CUDA_PATH:", os.environ.get("CUDA_PATH"))


CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8


In [1]:
import torch

rand = torch.randn(32,1,14,3)

In [4]:
x = rand.reshape((-1, 14, 3))

In [5]:
x.shape

torch.Size([32, 14, 3])

In [10]:
import numpy as np

data = np.load(r'C:\Users\Admin\OneDrive\Desktop\Desktop\DT-Pose\data\person_in_wifi_3d\test_data\keypoint\S51_10_333.npy', allow_pickle=True)

In [11]:
data.shape

(1, 14, 3)

In [1]:
from feeder.person_in_wifi_3d import PersonInWif3D, piw3_make_dataloader
import yaml
import torch
dataset_root = r"C:\Users\Admin\OneDrive\Desktop\Desktop\DT-Pose\data\person_in_wifi_3d"
with open(r"C:\Users\Admin\OneDrive\Desktop\Desktop\DT-Pose\config\person_in_wifi_3d\pose_config.yaml", 'r') as fd:
    config = yaml.load(fd, Loader=yaml.FullLoader)

train_dataset = PersonInWif3D('training', dataset_root, config['setting'])
val_dataset = PersonInWif3D('validation', dataset_root, config['setting'])
rng_generator = torch.manual_seed(config['init_rand_seed'])
train_loader = piw3_make_dataloader(train_dataset, is_training=True, generator=rng_generator, batch_size=32)
val_loader = piw3_make_dataloader(val_dataset, is_training=False, generator=rng_generator, batch_size=32)

all-person: Traning sample 89945.
all-person: Test sample 7824.


In [4]:
for batch in train_loader:
    print("=== Batch ===")
    print("input_wifi-csi:", batch['input_wifi-csi'].shape)
    print("output:", batch['output'].shape)           # pose padded
    print("person_num:", batch['person_num'])
    print("next frame:", batch['input_wifi-csi_next_frame'].shape)
    break

FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "c:\Users\Admin\anaconda3\envs\dfine\Lib\site-packages\torch\utils\data\_utils\worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\anaconda3\envs\dfine\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\anaconda3\envs\dfine\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "c:\Users\Admin\OneDrive\Desktop\Desktop\DT-Pose\feeder\person_in_wifi_3d.py", line 129, in __getitem__
    pose_data = np.array(np.load(item['keypoint_path']))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\anaconda3\envs\dfine\Lib\site-packages\numpy\lib\npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\OneDrive\\Desktop\\Desktop\\DT-Pose\\data\\person_in_wifi_3d\\train_data\\keypoint\\S11_09_172.npy'
